import { StyleSheet, Platform } from 'react-native';
import { theme } from './theme';

export const dashboardStyles = StyleSheet.create({
  // Scaffold general
  container: {
    flex: 1,
    backgroundColor: theme.colors.surface,
  },

  // Header superior fijo
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.margin,
    paddingVertical: theme.spacing.sm,
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(30, 19, 56, 0.04)',
  },
  headerBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconPill: {
    width: 40,
    height: 40,
    borderRadius: theme.radii.full,
    backgroundColor: theme.colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.secondaryContainer,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  headerBrandSub: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  headerTitle: {
    fontSize: theme.typography.fontSize.xl,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
    lineHeight: 22,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bellButton: {
    width: 42,
    height: 42,
    borderRadius: theme.radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceContainerLow,
    position: 'relative',
  },
  bellBadge: {
    position: 'absolute',
    top: 9,
    right: 9,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.secondaryContainer,
    borderWidth: 1.5,
    borderColor: theme.colors.surface,
  },
  profileAvatarButton: {
    padding: 2,
  },
  profileAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: theme.colors.secondaryContainer,
    backgroundColor: theme.colors.secondaryFixed,
  },

  // Saludo & Quick CTA
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.margin,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xs,
    gap: 12,
  },
  greetingTextContainer: {
    flex: 1,
    minWidth: 0,
    marginRight: 8,
  },
  greetingSub: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  greetingTitle: {
    fontSize: theme.typography.fontSize['2xl'],
    fontWeight: theme.typography.fontWeight.extrabold,
    color: theme.colors.textDark,
    marginTop: 2,
  },
  btnCreateGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.colors.secondaryContainer,
    paddingHorizontal: 14,
    height: 44,
    borderRadius: theme.radii.xl,
    flexShrink: 0,
    shadowColor: theme.colors.secondaryContainer,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 3,
  },
  btnCreateGroupText: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.primary,
  },

  // Banner Mascota Guacamayo ("Tip del Guaca")
  mascotBanner: {
    marginHorizontal: theme.spacing.margin,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    backgroundColor: '#20153A',
    borderRadius: theme.radii['2xl'],
    padding: 16,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#20153A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 4,
  },
  mascotBannerGlow: {
    position: 'absolute',
    right: -30,
    bottom: -30,
    width: 200,
    height: 200,
  },
  mascotBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mascotAvatarWrapper: {
    position: 'relative',
    width: 60,
    height: 60,
    borderRadius: theme.radii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  mascotAvatarImage: {
    width: 52,
    height: 52,
    resizeMode: 'contain',
  },
  mascotStarBadge: {
    position: 'absolute',
    bottom: -3,
    right: -3,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mascotStarText: {
    fontSize: 10,
    color: theme.colors.primary,
    fontWeight: 'bold',
  },
  mascotBannerBody: {
    flex: 1,
  },
  tipBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(254, 174, 16, 0.25)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.radii.full,
    marginBottom: 4,
  },
  tipBadgeText: {
    fontSize: 10,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.secondaryFixed,
    textTransform: 'uppercase',
  },
  mascotBannerTitle: {
    fontSize: theme.typography.fontSize.md,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
    lineHeight: 18,
  },
  mascotBannerSub: {
    fontSize: theme.typography.fontSize.xs,
    color: '#CEBFEF',
    marginTop: 3,
    lineHeight: 16,
  },
  mascotArrowButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Segmented Control / Tabs
  segmentedContainer: {
    marginHorizontal: theme.spacing.margin,
    marginVertical: theme.spacing.xs,
    backgroundColor: theme.colors.surfaceContainer,
    borderRadius: theme.radii.xl,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  segmentTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: theme.radii.lg,
  },
  segmentTabActive: {
    backgroundColor: theme.colors.surfaceCard,
    shadowColor: '#1E1338',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentText: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.semibold,
    color: theme.colors.textMuted,
  },
  segmentTextActive: {
    color: theme.colors.textDark,
    fontWeight: theme.typography.fontWeight.bold,
  },
  segmentBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: theme.radii.full,
    backgroundColor: theme.colors.surfaceContainerHighest,
  },
  segmentBadgeActive: {
    backgroundColor: theme.colors.secondaryContainer,
  },
  segmentBadgeText: {
    fontSize: 10,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textSecondary,
  },
  segmentBadgeTextActive: {
    color: theme.colors.primary,
  },

  // Tarjetas de Grupos
  cardsList: {
    paddingHorizontal: theme.spacing.margin,
    gap: 14,
    marginTop: 4,
  },
  groupCard: {
    backgroundColor: theme.colors.surfaceCard,
    borderRadius: theme.radii['2xl'],
    padding: 16,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#1E1338',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
  },
  cardAccentLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: theme.colors.secondaryContainer,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  cardTitleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  groupIconBox: {
    width: 48,
    height: 48,
    borderRadius: theme.radii.xl,
    backgroundColor: theme.colors.surfaceContainerHigh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupIconEmoji: {
    fontSize: 24,
  },
  groupTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  groupTitleText: {
    fontSize: theme.typography.fontSize.md,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
  },
  groupDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  groupDateText: {
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.textMuted,
  },

  // Status Badges
  statusBadgePending: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#C7E7FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radii.full,
  },
  statusDotPending: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#004C6C',
  },
  statusTextPending: {
    fontSize: 11,
    fontWeight: theme.typography.fontWeight.semibold,
    color: '#001E2E',
  },
  statusBadgeReady: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.secondaryContainer,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radii.full,
  },
  statusTextReady: {
    fontSize: 11,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.primary,
  },
  statusBadgeHistory: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: theme.radii.full,
    backgroundColor: theme.colors.surfaceContainer,
  },
  statusTextHistory: {
    fontSize: 11,
    fontWeight: theme.typography.fontWeight.medium,
    color: theme.colors.textMuted,
  },

  // Chips de Presupuesto y Modalidad
  chipsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  infoChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: theme.colors.surfaceContainerLow,
    borderRadius: theme.radii.lg,
    padding: 10,
  },
  chipIconBox: {
    width: 30,
    height: 30,
    borderRadius: theme.radii.md,
    backgroundColor: 'rgba(254, 174, 16, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipIconBoxAlt: {
    width: 30,
    height: 30,
    borderRadius: theme.radii.md,
    backgroundColor: theme.colors.surfaceContainerHighest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipLabel: {
    fontSize: 10,
    fontWeight: theme.typography.fontWeight.medium,
    color: theme.colors.textMuted,
  },
  chipValue: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
  },

  // Barra de progreso de confirmados
  progressSection: {
    marginBottom: 12,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  progressLabel: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.semibold,
    color: theme.colors.textDark,
  },
  progressCount: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.secondaryDark,
  },
  progressBarTrack: {
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.colors.surfaceContainerHighest,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: theme.colors.secondaryContainer,
  },

  // Footer de tarjeta (avatares y acción)
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  avatarStack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stackAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.colors.surfaceCard,
    marginLeft: -8,
  },
  stackAvatarEmoji: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.colors.surfaceCard,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  stackBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.colors.surfaceCard,
    backgroundColor: theme.colors.surfaceContainerHighest,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  stackBadgeText: {
    fontSize: 11,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textSecondary,
  },
  btnManage: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 14,
    height: 36,
    borderRadius: theme.radii.lg,
    backgroundColor: theme.colors.surfaceContainerHigh,
  },
  btnManageText: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
  },

  // Tarjeta destacada de Sobre ("Tienes tu sobre sellado")
  envelopeHighlightCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.surfaceContainer,
    borderRadius: theme.radii.xl,
    padding: 12,
    marginBottom: 10,
  },
  envelopeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  envelopeIconPill: {
    width: 40,
    height: 40,
    borderRadius: theme.radii.lg,
    backgroundColor: theme.colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.secondaryContainer,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
    flexShrink: 0,
  },
  envelopeTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  envelopeTitle: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
  },
  envelopeSub: {
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.textMuted,
    marginTop: 1,
  },
  btnOpenEnvelope: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 12,
    height: 34,
    borderRadius: theme.radii.md,
    flexShrink: 0,
  },
  btnOpenEnvelopeText: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
  },

  // Mini banner "¿Te llegó un código?"
  inviteBanner: {
    marginHorizontal: theme.spacing.margin,
    marginVertical: theme.spacing.md,
    backgroundColor: theme.colors.surfaceContainer,
    borderRadius: theme.radii['2xl'],
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  inviteLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  inviteIconBox: {
    width: 40,
    height: 40,
    borderRadius: theme.radii.full,
    backgroundColor: 'rgba(254, 174, 16, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  inviteTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  inviteTitle: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
  },
  inviteSub: {
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  btnInviteEnter: {
    backgroundColor: theme.colors.surfaceCard,
    paddingHorizontal: 16,
    height: 38,
    borderRadius: theme.radii.lg,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    shadowColor: '#1E1338',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  btnInviteEnterText: {
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.textDark,
  },

  // Floating Tab Bar (Menú Flotante estilo píldora)
  floatingTabBarContainer: {
    position: 'absolute',
    left: 20,
    right: 20,
    zIndex: 99,
  },
  floatingTabBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 34,
    height: 64,
    paddingHorizontal: 8,
    shadowColor: '#1E1338',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(240, 236, 249, 0.8)',
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  tabIconWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: theme.typography.fontWeight.semibold,
    color: theme.colors.textMuted,
  },
  tabLabelActive: {
    color: theme.colors.primary,
    fontWeight: theme.typography.fontWeight.bold,
  },
});

export default dashboardStyles;
